package Gui;

import Back_End.Calculadora;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KleinCruz
 */
public class Calc_Edit extends javax.swing.JFrame {

    /**
     * Creates new form Calc_Edit
     */
    public Calc_Edit() {
        initComponents();
        calculadora = new Calculadora();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Linha_Painel = new javax.swing.JPanel();
        Painel = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Num_1 = new javax.swing.JButton();
        Num_2 = new javax.swing.JButton();
        Num_3 = new javax.swing.JButton();
        Result = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Num_4 = new javax.swing.JButton();
        Num_5 = new javax.swing.JButton();
        Num_6 = new javax.swing.JButton();
        Backspace = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Num_7 = new javax.swing.JButton();
        Num_8 = new javax.swing.JButton();
        Num_9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Open_Par = new javax.swing.JButton();
        Num_0 = new javax.swing.JButton();
        Close_Par = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Plus = new javax.swing.JButton();
        Minus = new javax.swing.JButton();
        Multi = new javax.swing.JButton();
        Div = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new java.awt.GridLayout(0, 1, 1, 1));

        Linha_Painel.setBackground(new java.awt.Color(255, 255, 255));
        Linha_Painel.setForeground(new java.awt.Color(255, 255, 255));
        Linha_Painel.setLayout(new java.awt.GridLayout(1, 0, 1, 0));

        Painel.setBackground(new java.awt.Color(45, 76, 70));
        Painel.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Painel.setForeground(new java.awt.Color(230, 230, 230));
        Painel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Linha_Painel.add(Painel);

        getContentPane().add(Linha_Painel);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 1, 0));

        Num_1.setBackground(new java.awt.Color(45, 76, 70));
        Num_1.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Num_1.setForeground(new java.awt.Color(230, 230, 230));
        Num_1.setText("1");
        Num_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_1ActionPerformed(evt);
            }
        });
        jPanel2.add(Num_1);

        Num_2.setBackground(new java.awt.Color(45, 76, 70));
        Num_2.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Num_2.setForeground(new java.awt.Color(230, 230, 230));
        Num_2.setText("2");
        Num_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_2ActionPerformed(evt);
            }
        });
        jPanel2.add(Num_2);

        Num_3.setBackground(new java.awt.Color(45, 76, 70));
        Num_3.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Num_3.setForeground(new java.awt.Color(230, 230, 230));
        Num_3.setText("3");
        Num_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_3ActionPerformed(evt);
            }
        });
        jPanel2.add(Num_3);

        Result.setBackground(new java.awt.Color(45, 76, 70));
        Result.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Result.setForeground(new java.awt.Color(230, 230, 230));
        Result.setText("=");
        Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultActionPerformed(evt);
            }
        });
        jPanel2.add(Result);

        getContentPane().add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 1, 0));

        Num_4.setBackground(new java.awt.Color(45, 76, 70));
        Num_4.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Num_4.setForeground(new java.awt.Color(230, 230, 230));
        Num_4.setText("4");
        Num_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_4ActionPerformed(evt);
            }
        });
        jPanel3.add(Num_4);

        Num_5.setBackground(new java.awt.Color(45, 76, 70));
        Num_5.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Num_5.setForeground(new java.awt.Color(230, 230, 230));
        Num_5.setText("5");
        Num_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_5ActionPerformed(evt);
            }
        });
        jPanel3.add(Num_5);

        Num_6.setBackground(new java.awt.Color(45, 76, 70));
        Num_6.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Num_6.setForeground(new java.awt.Color(230, 230, 230));
        Num_6.setText("6");
        Num_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_6ActionPerformed(evt);
            }
        });
        jPanel3.add(Num_6);

        Backspace.setBackground(new java.awt.Color(45, 76, 70));
        Backspace.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Backspace.setForeground(new java.awt.Color(230, 230, 230));
        Backspace.setText("<X");
        Backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackspaceActionPerformed(evt);
            }
        });
        jPanel3.add(Backspace);

        getContentPane().add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 1, 0));

        Num_7.setBackground(new java.awt.Color(45, 76, 70));
        Num_7.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Num_7.setForeground(new java.awt.Color(230, 230, 230));
        Num_7.setText("7");
        Num_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_7ActionPerformed(evt);
            }
        });
        jPanel4.add(Num_7);

        Num_8.setBackground(new java.awt.Color(45, 76, 70));
        Num_8.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Num_8.setForeground(new java.awt.Color(230, 230, 230));
        Num_8.setText("8");
        Num_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_8ActionPerformed(evt);
            }
        });
        jPanel4.add(Num_8);

        Num_9.setBackground(new java.awt.Color(45, 76, 70));
        Num_9.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Num_9.setForeground(new java.awt.Color(230, 230, 230));
        Num_9.setText("9");
        Num_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_9ActionPerformed(evt);
            }
        });
        jPanel4.add(Num_9);

        jButton10.setBackground(new java.awt.Color(45, 76, 70));
        jPanel4.add(jButton10);

        getContentPane().add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 1, 0));

        Open_Par.setBackground(new java.awt.Color(45, 76, 70));
        Open_Par.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Open_Par.setForeground(new java.awt.Color(230, 230, 230));
        Open_Par.setText("(");
        Open_Par.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_ParActionPerformed(evt);
            }
        });
        jPanel5.add(Open_Par);

        Num_0.setBackground(new java.awt.Color(45, 76, 70));
        Num_0.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Num_0.setForeground(new java.awt.Color(230, 230, 230));
        Num_0.setText("0");
        Num_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_0ActionPerformed(evt);
            }
        });
        jPanel5.add(Num_0);

        Close_Par.setBackground(new java.awt.Color(45, 76, 70));
        Close_Par.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Close_Par.setForeground(new java.awt.Color(230, 230, 230));
        Close_Par.setText(")");
        Close_Par.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_ParActionPerformed(evt);
            }
        });
        jPanel5.add(Close_Par);

        jButton16.setBackground(new java.awt.Color(45, 76, 70));
        jPanel5.add(jButton16);

        getContentPane().add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 1, 0));

        Plus.setBackground(new java.awt.Color(45, 76, 70));
        Plus.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Plus.setForeground(new java.awt.Color(230, 230, 230));
        Plus.setText("+");
        Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusActionPerformed(evt);
            }
        });
        jPanel6.add(Plus);

        Minus.setBackground(new java.awt.Color(45, 76, 70));
        Minus.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Minus.setForeground(new java.awt.Color(230, 230, 230));
        Minus.setText("-");
        Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusActionPerformed(evt);
            }
        });
        jPanel6.add(Minus);

        Multi.setBackground(new java.awt.Color(45, 76, 70));
        Multi.setFont(new java.awt.Font("Courier New", 0, 30)); // NOI18N
        Multi.setForeground(new java.awt.Color(230, 230, 230));
        Multi.setText("*");
        Multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiActionPerformed(evt);
            }
        });
        jPanel6.add(Multi);

        Div.setBackground(new java.awt.Color(45, 76, 70));
        Div.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        Div.setForeground(new java.awt.Color(230, 230, 230));
        Div.setText("/");
        Div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivActionPerformed(evt);
            }
        });
        jPanel6.add(Div);

        getContentPane().add(jPanel6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultActionPerformed
     String Resultado = Painel.getText();
     
     while( Resultado.contains("+")||Resultado.contains("-")||
            Resultado.contains("*")||Resultado.contains("/")||
            Resultado.contains("(") ){
        if(Resultado.contains("+")) {
            String[] Calcular = Resultado.split("\\+");
            Integer primeiro = Integer.parseInt(Calcular[0]);
            Integer segundo = Integer.parseInt(Calcular[1]);
            Integer Result = calculadora.soma(primeiro, segundo);
            Painel.setText(Integer.toString(Result));
        } if(Resultado.contains("-")) {
            String[] Calcular = Resultado.split("\\-");
            Integer primeiro = Integer.parseInt(Calcular[0]);
            Integer segundo = Integer.parseInt(Calcular[1]);
            Integer Result = calculadora.subt(primeiro, segundo);
            Painel.setText(Integer.toString(Result));
        } if(Resultado.contains("*")) {
            String[] Calcular = Resultado.split("\\*");
            Integer primeiro = Integer.parseInt(Calcular[0]);
            Integer segundo = Integer.parseInt(Calcular[1]);
            Integer Result = calculadora.mult(primeiro, segundo);
            Painel.setText(Integer.toString(Result));
        } if(Resultado.contains("/")) {
            String[] Calcular = Resultado.split("\\/");
            Integer primeiro = Integer.parseInt(Calcular[0]);
            Integer segundo = Integer.parseInt(Calcular[1]);
            Integer Result = calculadora.divi(primeiro, segundo);
            Painel.setText(Integer.toString(Result));
        } 
  
    }
    }//GEN-LAST:event_ResultActionPerformed

    private void Num_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_1ActionPerformed
       Painel.setText(Painel.getText() + "1");
    }//GEN-LAST:event_Num_1ActionPerformed

    private void Num_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_2ActionPerformed
       Painel.setText(Painel.getText() + "2"); 
    }//GEN-LAST:event_Num_2ActionPerformed

    private void Num_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_3ActionPerformed
       Painel.setText(Painel.getText() + "3"); 
    }//GEN-LAST:event_Num_3ActionPerformed

    private void Num_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_4ActionPerformed
        Painel.setText(Painel.getText() + "4");
    }//GEN-LAST:event_Num_4ActionPerformed

    private void Num_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_5ActionPerformed
        Painel.setText(Painel.getText() + "5");
    }//GEN-LAST:event_Num_5ActionPerformed

    private void Num_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_6ActionPerformed
        Painel.setText(Painel.getText() + "6");
    }//GEN-LAST:event_Num_6ActionPerformed

    private void Num_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_7ActionPerformed
       Painel.setText(Painel.getText() + "7"); 
    }//GEN-LAST:event_Num_7ActionPerformed

    private void Num_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_8ActionPerformed
        Painel.setText(Painel.getText() + "8");
    }//GEN-LAST:event_Num_8ActionPerformed

    private void Num_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_9ActionPerformed
        Painel.setText(Painel.getText() + "9");
    }//GEN-LAST:event_Num_9ActionPerformed

    private void Num_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_0ActionPerformed
        Painel.setText(Painel.getText() + "0");
    }//GEN-LAST:event_Num_0ActionPerformed

    private void Open_ParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_ParActionPerformed
        Painel.setText(Painel.getText() + "(");
    }//GEN-LAST:event_Open_ParActionPerformed

    private void Close_ParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_ParActionPerformed
        Painel.setText(Painel.getText() + ")");
    }//GEN-LAST:event_Close_ParActionPerformed

    private void PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusActionPerformed
        Painel.setText(Painel.getText() + "+");
    }//GEN-LAST:event_PlusActionPerformed

    private void MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusActionPerformed
        Painel.setText(Painel.getText() + "-");
    }//GEN-LAST:event_MinusActionPerformed

    private void MultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiActionPerformed
        Painel.setText(Painel.getText() + "*");
    }//GEN-LAST:event_MultiActionPerformed

    private void DivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivActionPerformed
        Painel.setText(Painel.getText() + "/");
    }//GEN-LAST:event_DivActionPerformed

    private void BackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackspaceActionPerformed
        String mod = Painel.getText();
        mod = mod.substring(0, mod.length() - 1);
        Painel.setText(mod);
        
    }//GEN-LAST:event_BackspaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc_Edit().setVisible(true);
            }
        });
    }
    private Calculadora calculadora;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backspace;
    private javax.swing.JButton Close_Par;
    private javax.swing.JButton Div;
    private javax.swing.JPanel Linha_Painel;
    private javax.swing.JButton Minus;
    private javax.swing.JButton Multi;
    private javax.swing.JButton Num_0;
    private javax.swing.JButton Num_1;
    private javax.swing.JButton Num_2;
    private javax.swing.JButton Num_3;
    private javax.swing.JButton Num_4;
    private javax.swing.JButton Num_5;
    private javax.swing.JButton Num_6;
    private javax.swing.JButton Num_7;
    private javax.swing.JButton Num_8;
    private javax.swing.JButton Num_9;
    private javax.swing.JButton Open_Par;
    private javax.swing.JTextField Painel;
    private javax.swing.JButton Plus;
    private javax.swing.JButton Result;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
